pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                //
            }
        }
        stage('Test') {
            steps {
                //
            }
        }
        stage('Run') {
            steps {
                //
            }
        }
    }
}